### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by SafaeQ** [TijClass/Contact_App_Safae_QN#1]
i have a problem how to set logo in my code

**Comment by abdelazizbardich** [comment]
can you please share you code ?

**Comment by tijaniabdellatif** [comment]
@SafaeQ  Read the instruction about the issues in this page 
[Instructions](https://github.com/TijClass/Contact_application/issues/4)

**Comment by SafaeQ** [comment]
<span class="logo">TM</span>
    <div class="logout">
        
        <h1 class="title">My Web App</h1>
        <button class="btn4" type="submit" form="nameform" value="Send"> < Logout</button>
    </div>
   
    <div class="listcont">
        <h3>Contact List</h3>
        <div class="addin">
        <div class="form-group has-search">
            <span class="fa fa-search form-control-feedback"></span>
            <input class="Search" type="text" class="form-control" placeholder="Search">
        </div>
        <div >
            <button class="btn5" name="submit" value="send" type="submit">Add a Person</button>
        </div>
        </div>
    </div>

**Comment by SafaeQ** [comment]
/* logout */
  .logout{
    background-color:#BB6BB5;
    position: relative;
    height: 10vh;
    width: 90%;
    left: 9%;
    
  }
  .btn4{
    position: absolute;
    right: 15px;
    top: 16px;
  }
  .title{
    float: left;
    padding-left: 9px;
  }
  .listcont{
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 1fr 1fr;
  
  }
  .addin{
    grid-area: 2/3 / 3/4;
    display: flex;
    position: relative;
  }
  
  .btn5{
    margin-top: 8px;
    padding: 5px;
    background-color: #fffdff;
    color: rgb(0, 0, 0);
    
    cursor: pointer;
    
    box-shadow: 10px 5px 5px #75016D;
  }
  
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 90%;
    float: right;
    margin-right: 18px;
    box-shadow: 10px 5px 5px #e37beb;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  .line1{
    background-color: #F7ADF4;
  }
  .line2{
    background-color:#F9BFFD;
  }
  span{
    background-color: black;
    color: white;
    float: right;
    border-radius: 50px;
    width: 17px;
  }
  
  .logo1{
    height: auto;
    background-color: white;
    float: left;
    width: 28px;
    border: 1px solid black;
    color: black; 
  }

**Comment by tijaniabdellatif** [comment]
@SafaeQ  didn't understant the problem so try to explain more

**Comment by abdelazizbardich** [comment]
Can you explain more ??
